apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
 name: mta
spec:
 serviceName: mta-service
 replicas: 4
 template:
   metadata:
     labels:
       app: mta
   spec:
     containers:
     - name: mta
       image: 294256424338.dkr.ecr.us-west-2.amazonaws.com/zimbra-mta:latest
       imagePullPolicy: Always
       volumeMounts:
       - name: zimbra-volume
         mountPath: /etc/config
       env:
       - name: EXT_DOMAIN
         value: arvin-k8s.cascadeo.info
       - name: EXT_HOST
         value: zimbra
       - name: PASSWORD
         value: temp1234
       - name: NS
         valueFrom:
           fieldRef:
             fieldPath: metadata.namespace
       ports:
       - containerPort: 22
       - containerPort: 25
       - containerPort: 80
       - containerPort: 110
       - containerPort: 143
       - containerPort: 389
       - containerPort: 443
       - containerPort: 465
       - containerPort: 587
       - containerPort: 993
       - containerPort: 995
       - containerPort: 7071
       - containerPort: 8080
       - containerPort: 8443
       readinessProbe:
         exec:
           command:
           - /bin/sh
           - -c
           - test $(service zimbra status | grep Stopped | wc -l) -eq 0
         initialDelaySeconds: 600
         periodSeconds: 10
       livenessProbe:
         exec:
           command:
           - /bin/sh
           - -c
           - test $(service zimbra status | grep Stopped | wc -l) -eq 0
         initialDelaySeconds: 900
         periodSeconds: 15
     volumes:
     - name: zimbra-volume
       configMap:
         name: zimbra-mta
         items:
         - key: zimbra-properties
           path: zimbra.conf
     imagePullSecrets:
     - name: myregistrykey
